### ISSUE TITLE
Missing images while trying to backup a larger Trello board

### ISSUE THREAD

**Issue by 2447254731** [mattab/trello-backup#56] opened 2021-05-15 16:23 UTC
Hi!
I'm trying to backup my trello board that with tons of my artworks, using Apache on Windows.
But some images was missing, although the program has downloaded many of them.
And I found that most of the lost images are created and uploaded before a certain time point, looks like a date from a year or less ago.
Fortunately, there is no text missing.
And I found this problem in some similar Trello-backuping programs like Wekan, There's an ([issue](https://github.com/wekan/wekan/issues/3175)) that is a bit close to this situation. This program can backup a Trello board to a local environment, and while I trying to use this one (still on Windows), it has failed downloading some images and those missing things are still before a similar time point.
You can contact me if you need me providing logs or other files.

**Comment by xet7** [comment] 2023-05-29 22:45
Moved to #4877

**Comment by R-omk** [comment] 2023-09-18 13:56
The problem is that now attachments are taken from the last “actions” (the number of last actions is limited.), and not from card objects.

https://github.com/mattab/trello-backup/blob/2ed50f82e373d2b034f4bdce6420c5a1af53b8c8/trello-backup.php#L152-L157

**Comment by R-omk** [comment] 2023-09-18 15:18
https://github.com/mattab/trello-backup/pull/63

**Comment by mattab** [comment] 2023-09-29 04:53
This might be fixed in the latest version @2447254731 - thanks to @R-omk pull request? please let me know if it's still failing, i will reopen

**Closed by mattab** 2023-09-29 04:53 UTC
